run:
  skip-dirs:
    - tpl
    - common
    - p1480
    - p1646

linters:
  enable-all: true
  disable:
    # deprecated
    - exhaustivestruct
    - golint
    - ifshort
    - scopelint
    - maligned
    - interfacer
    - deadcode
    - structcheck
    - nosnakecase
    - varcheck

    # 1.18+
    # https://github.com/golangci/golangci-lint/issues/2649
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

    # useless
    - gomnd # magic numbers are ok
    - testpackage # no need for separate test package
    - wsl # whitespaces are to opinonated
    - forcetypeassert # i know what i'm doing

linters-settings:
  varnamelen:
    ignore-names:
      # common names for iterators
      - i
      - j

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - varnamelen
        - funlen
