name: Go Code Quality

on:
  push:
    branches:
      - main
    paths:
      - go

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go/go.mod
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./go
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go/go.mod
      - working-directory: ./go
        run: go test -v -race ./...
